# ${GPU} ${index} ${hours} ${script.py} ${profile} ${layer} ${neurons} ${attempt}
echo "#!/bin/bash -l"
echo "#PBS -N ${4:0:2}-$1-$2"
echo ""
echo "#PBS -l walltime=$3:00:00"
echo "#PBS -l mem=150GB"
echo "#PBS -l ncpus=1"
echo "#PBS -l ngpus=1"
echo "#PBS -l gputype=$1"
echo ""
echo "export HDF5_USE_FILE_LOCKING='FALSE'"
echo "module load tensorflow/2.3.1-fosscuda-2019b-python-3.7.4"
echo "python -m pip install --upgrade pip"
echo "python -m pip install --user matplotlib pandas numpy sklearn scipy tqdm openpyxl"
echo "python -m pip install ~/artifacts/tensorflow_addons-0.13.0-cp37-cp37m-linux_x86_64.whl"
echo ""
echo "cd \$PBS_O_WORKDIR"
echo ""
echo ""
echo "python $4 -d False -e 100 -g 0 -p $5 -l $6 -n $7 -a $8 -o $9 -r 0.0001"
